import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { dir } from "i18next"; 
import { languages } from "../i18n/setting"; 
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quản lý sinh viên",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string }
}) {
  return (
    <html lang={params.lang} dir={dir(params.lang)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster/>
        {children}
      </body>
    </html>
  );
}
